package com.vectis.erp.data.model

import com.google.gson.annotations.SerializedName

/**
 * Request payload sent by Android app to POST /api/devices/pair
 */
data class PairingRequest(
    @SerializedName("code")
    val code: String,

    @SerializedName("device_name")
    val deviceName: String? = null,

    @SerializedName("device_model")
    val deviceModel: String? = null
)

/**
 * Response payload returned by backend on device pairing
 */
data class PairingResponse(
    @SerializedName("success")
    val success: Boolean = false,

    @SerializedName("deviceId")
    val deviceId: String? = null,

    @SerializedName("deviceToken")
    val deviceToken: String? = null,

    @SerializedName("deviceName")
    val deviceName: String? = null,

    @SerializedName("message")
    val message: String? = null,

    @SerializedName("error")
    val error: String? = null
)

/**
 * QR Code payload generated by Web ERP
 * e.g. {"version":"1.0","action":"pair_device","deviceId":"dev-123","code":"482731","expiresAt":"..."}
 */
data class QrPairingPayload(
    @SerializedName("version")
    val version: String? = "1.0",

    @SerializedName("action")
    val action: String? = "pair_device",

    @SerializedName("deviceId")
    val deviceId: String? = null,

    @SerializedName("code")
    val code: String = "",

    @SerializedName("expiresAt")
    val expiresAt: String? = null
)
